[build]
  command = "npm install && npm run build"
  
  baseURL = "/"

[[redirects]]
  from = "https://creative-daffodil-d987ea.netlify.app/"
  to = "https://fullstackportfolio.onrender.com/"
  status = 200